format = """
$username\
$hostname\
$shlvl\
$singularity\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$custom\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$sudo\
$kubernetes\
$battery\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$shell\
$character"""


[kubernetes]
disabled = false
format = ' | [$symbol$context(\($namespace\))]($style)'
[kubernetes.context_aliases]
"gke_akkoordzoeker_europe-west4-a_akkoordzoeker" = "akz"
"default/api-rhos-ota-ynna-p1-openshiftapps-com:6443/erwin.dekeijzer" = "RHOS-OTA"
"gke_ckad-study-359208_europe-west4_autopilot-cluster-1" = "ckad"

[golang]
format = " | [$symbol$version](bold cyan)"

[gcloud]
format = " | [$symbol$project]($style)"
disabled = true

[cmd_duration]
min_time = 400
show_milliseconds = true

[custom.codedirs]
command = "/Users/erwindekeijzer/bin/repolink.sh"
when = """ true """
