
{{- $helixVersion := "23.10"}}
{{- $helixArch := "x86_64"}}
{{- $helixOS := "linux"}}
{{ if eq .chezmoi.os "darwin" }}
{{- $helixOS = "macos" }}
{{- $helixArch = "aarch64" }}
{{ end -}}

{{- $helixPackageName := printf "helix-%s-%s-%s" $helixVersion $helixArch $helixOS }}

{{- $helixArchiveUrl := printf "https://github.com/helix-editor/helix/releases/download/%s/%s.tar.xz" $helixVersion $helixPackageName -}}

[".local/bin/hx"]
    type = "archive-file"
    executable = true
    path = {{printf "%s/hx" $helixPackageName | quote}}
    url = {{ $helixArchiveUrl | quote }}

[".config/helix"]
    type = "archive"
    stripComponents = 1
    include = [
        {{printf "%s/runtime/**" $helixPackageName | quote}},
    ]
    url = {{ $helixArchiveUrl | quote }}

{{ $ageVersion := "1.1.1" -}}
[".local/bin/age"]
    type = "archive-file"
    url = "https://github.com/FiloSottile/age/releases/download/v{{ $ageVersion }}/age-v{{ $ageVersion }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    path = "age/age"

