import = [
    "~/.config/alacritty/themes/themes/blood_moon.toml"
]

[font]
size = 15.0

[font.normal]
family = "CaskaydiaCove Nerd Font"

[window]
dimensions = { columns = 200, lines=60 }
option_as_alt = "Both"
