theme = "tokyonight"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
auto-pairs = false
auto-save = true
bufferline = "multiple"
color-modes = true
true-color = true

[editor.statusline]
center = [ "version-control" ]

[editor.lsp]
display-inlay-hints	= true

[keys.normal]

L = "goto_next_buffer"
H = "goto_previous_buffer"
