[tools]
age = "latest"
bat = "latest"
fd = "latest"
fzf = "latest"
direnv = "latest"
lazygit = "latest"
gitui = "latest"
lsd = "latest"
node = "20"
ripgrep = "latest"
starship = "latest"
xh = "latest"
zellij = "latest"
zoxide = "latest"
task = "latest"
kubectl = "latest"
k9s = "latest"
helix = "latest"
"aqua:helix-editor/helix" = "latest"
"aqua:atuinsh/atuin" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:xyazi/yazi" = "latest"
